---
# schema for sending model data in vellum
types:
    '*':
        properties: [TYPE]
    Background:
        desc: The background image of the map
        properties: [uri, view, scale100px]
    ObscurementMask:
        desc: an image overlay that defines the visible/masked areas of the map
        properties: [uri]
    Character:
        desc: A PC or NPC
        properties: [uri, corner, size, name]
    Note:
        desc: A written text blurb placed on the map
        properties: [uri, text, corner, title]
    Sound:
        desc: A sound effect placed on the map
        properties: [uri, corner]
    Drawing:
        desc: A vector figure drawn on the map
        properties: [uri, corner]
    Map:
        desc: A grouping type for organizing all the models into a container
        properties: [models, name, description]

---
# schema for sending model data in vellum
types:
    '*':
        properties: [TYPE]
    Background:
        desc: The background image of the map
        properties: [uri, view, scale100px]
    ObscurementMask:
        desc: an image overlay that defines the visible/masked areas of the map
        properties: [uri]
    Character:
        desc: A PC or NPC
        properties: [uri, corner, size, name]
    Note:
        desc: A written text blurb placed on the map
        properties: [uri, text, corner, title]
    Sound:
        desc: A sound effect placed on the map
        properties: [uri, corner]
    Drawing:
        desc: A vector figure drawn on the map
        properties: [uri, corner]
    Map:
        desc: A grouping type for organizing all the models into a container
        properties: [models, name, description]

